set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_led[0]}]
set_property DRIVE 12 [get_ports {rgb_led[2]}]
set_property DRIVE 12 [get_ports {rgb_led[1]}]
set_property DRIVE 12 [get_ports {rgb_led[0]}]
set_property SLEW SLOW [get_ports {rgb_led[2]}]
set_property SLEW SLOW [get_ports {rgb_led[1]}]
set_property SLEW SLOW [get_ports {rgb_led[0]}]
set_property PACKAGE_PIN E1 [get_ports {rgb_led[2]}]
set_property PACKAGE_PIN F6 [get_ports {rgb_led[1]}]
set_property PACKAGE_PIN G6 [get_ports {rgb_led[0]}]

set_property OFFCHIP_TERM NONE [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports clkin]
set_property PACKAGE_PIN E3 [get_ports clkin]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A9 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]
set_property DRIVE 12 [get_ports tx]
set_property SLEW SLOW [get_ports tx]
set_property PACKAGE_PIN D10 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN C2 [get_ports rst_n]

#set_property PACKAGE_PIN K5 [get_ports ddr3_dq[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[0]]
#set_property PACKAGE_PIN L3 [get_ports ddr3_dq[1]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[1]]
#set_property PACKAGE_PIN K3 [get_ports ddr3_dq[2]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[2]]
#set_property PACKAGE_PIN L6 [get_ports ddr3_dq[3]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[3]]
#set_property PACKAGE_PIN M3 [get_ports ddr3_dq[4]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[4]]
#set_property PACKAGE_PIN M1 [get_ports ddr3_dq[5]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[5]]
#set_property PACKAGE_PIN L4 [get_ports ddr3_dq[6]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[6]]
#set_property PACKAGE_PIN M2 [get_ports ddr3_dq[7]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[7]]
#set_property PACKAGE_PIN V4 [get_ports ddr3_dq[8]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[8]]
#set_property PACKAGE_PIN T5 [get_ports ddr3_dq[9]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[9]]
#set_property PACKAGE_PIN U4 [get_ports ddr3_dq[10]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[10]]
#set_property PACKAGE_PIN V5 [get_ports ddr3_dq[11]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[11]]
#set_property PACKAGE_PIN V1 [get_ports ddr3_dq[12]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[12]]
#set_property PACKAGE_PIN T3 [get_ports ddr3_dq[13]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[13]]
#set_property PACKAGE_PIN U3 [get_ports ddr3_dq[14]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[14]]
#set_property PACKAGE_PIN R3 [get_ports ddr3_dq[15]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dq[15]]
#set_property PACKAGE_PIN L1 [get_ports ddr3_dm[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dm[0]]
#set_property PACKAGE_PIN U1 [get_ports ddr3_dm[1]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_dm[1]]
#set_property PACKAGE_PIN N2 [get_ports ddr3_dqs_p[0]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_dqs_p[0]]
#set_property PACKAGE_PIN N1 [get_ports ddr3_dqs_n[0]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_dqs_n[0]]
#set_property PACKAGE_PIN U2 [get_ports ddr3_dqs_p[1]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_dqs_p[1]]
#set_property PACKAGE_PIN V2 [get_ports ddr3_dqs_n[1]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_dqs_n[1]]
#set_property PACKAGE_PIN T8 [get_ports ddr3_addr[13]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[13]]
#set_property PACKAGE_PIN T6 [get_ports ddr3_addr[12]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[12]]
#set_property PACKAGE_PIN U6 [get_ports ddr3_addr[11]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[11]]
#set_property PACKAGE_PIN R6 [get_ports ddr3_addr[10]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[10]]
#set_property PACKAGE_PIN V7 [get_ports ddr3_addr[9]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[9]]
#set_property PACKAGE_PIN R8 [get_ports ddr3_addr[8]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[8]]
#set_property PACKAGE_PIN U7 [get_ports ddr3_addr[7]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[7]]
#set_property PACKAGE_PIN V6 [get_ports ddr3_addr[6]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[6]]
#set_property PACKAGE_PIN R7 [get_ports ddr3_addr[5]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[5]]
#set_property PACKAGE_PIN N6 [get_ports ddr3_addr[4]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[4]]
#set_property PACKAGE_PIN T1 [get_ports ddr3_addr[3]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[3]]
#set_property PACKAGE_PIN N4 [get_ports ddr3_addr[2]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[2]]
#set_property PACKAGE_PIN M6 [get_ports ddr3_addr[1]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[1]]
#set_property PACKAGE_PIN R2 [get_ports ddr3_addr[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_addr[0]]
#set_property PACKAGE_PIN P2 [get_ports ddr3_ba[2]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_ba[2]]
#set_property PACKAGE_PIN P4 [get_ports ddr3_ba[1]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_ba[1]]
#set_property PACKAGE_PIN R1 [get_ports ddr3_ba[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_ba[0]]
#set_property PACKAGE_PIN U9 [get_ports ddr3_ck_p[0]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_ck_p[0]]
#set_property PACKAGE_PIN V9 [get_ports ddr3_ck_n[0]]
#set_property IOSTANDARD DIFF_SSTL135 [get_ports ddr3_ck_n[0]]
#set_property PACKAGE_PIN P3 [get_ports ddr3_ras_n]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_ras_n]
#set_property PACKAGE_PIN M4 [get_ports ddr3_cas_n]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_cas_n]
#set_property PACKAGE_PIN P5 [get_ports ddr3_we_n]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_we_n]
#set_property PACKAGE_PIN K6 [get_ports ddr3_reset_n]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_reset_n]
#set_property PACKAGE_PIN N5 [get_ports ddr3_cke[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_cke[0]]
#set_property PACKAGE_PIN R5 [get_ports ddr3_odt[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_odt[0]]
#set_property PACKAGE_PIN U8 [get_ports ddr3_cs_n[0]]
#set_property IOSTANDARD SSTL135 [get_ports ddr3_cs_n[0]]

#revert back to original instance
#current_instance -quiet

set_property OFFCHIP_TERM NONE [get_ports tx]
set_property OFFCHIP_TERM NONE [get_ports rgb_led[2]]
set_property OFFCHIP_TERM NONE [get_ports rgb_led[1]]
set_property OFFCHIP_TERM NONE [get_ports rgb_led[0]]
create_clock -period 10.000 -name clkin -waveform {0.000 5.000} [get_ports clkin]

set_input_delay -clock [get_clocks  clkin] -min -add_delay 1.000 [get_ports rst_n]
set_input_delay -clock [get_clocks  clkin] -max -add_delay 1.000 [get_ports rst_n]
set_input_delay -clock [get_clocks  clkin] -min -add_delay 1.000 [get_ports rx]
set_input_delay -clock [get_clocks  clkin] -max -add_delay 1.000 [get_ports rx]
set_output_delay -clock [get_clocks clkin] -min -add_delay -3.000 [get_ports tx]
set_output_delay -clock [get_clocks clkin] -max -add_delay -3.000 [get_ports tx]
set_output_delay -clock [get_clocks -of_objects [get_nets mclk]] -min -add_delay -3.000 [get_ports {rgb_led[*]}]
set_output_delay -clock [get_clocks -of_objects [get_nets mclk]] -max -add_delay -3.000 [get_ports {rgb_led[*]}]

set_clock_groups -group [get_clocks -of_objects [get_nets clk]] -group [get_clocks -of_objects [get_nets mclk]] -asynchronous
#
